<!DOCTYPE html>
<html lang="en">
<head>
    <?php include __DIR__ . '/partials/head.html'; ?>
</head>
<body>
<h1 class="text-center bg-light-subtle w-50 mx-auto my-0">Register New User</h1>

    <?php include __DIR__ . '/partials/navBarLoggedOut.html'; ?>
<div class="border border-4 border-primary-subtle rounded-4 w-50 mx-auto text-center p-5 bg-light-subtle">

<?php if (!empty($message)): ?>
    <p class="text-danger"><?= htmlspecialchars($message) ?></p>
<?php endif; ?>
    <form method="post" action="/register">
        <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            <input type="text" class="form-control w-50 mx-auto" id="username" name="username">
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email:</label>
            <input type="email" class="form-control w-50 mx-auto" id="email" name="email">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password:</label>
            <input type="password" class="form-control w-50 mx-auto" id="password" name="password">
        </div>

        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

</body>
</html>