<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register New User</title>
</head>
<body>
<h1>Register New User</h1>
<form method="post" action="/register">
    <label>Username:
        <input type="text" name="username">
    </label>
    <label>Email:
        <input type="email" name="email">
    </label>
    <label>Password:
        <input type="password" name="password">
    </label>
    <input type="submit">
</form>
</body>
</html>